updated the tests workflow to generate coverage reports

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -10,27 +10,59 @@ on:
       - pyproject.toml
 
 jobs:
-  run_tests:
-    name: Run project tests
+  run_tests_with_coverage:
+    name: Run tests with coverage
     runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
 
     steps:
       - name: Checkout
         uses: actions/checkout@v4
 
-      - name: Set up Python ${{ matrix.python-version }}
+      - name: Set up Python
         uses: actions/setup-python@v5
         with:
-          python-version: ${{ matrix.python-version }}
+          python-version: |
+            3.9
+            3.10
+            3.11
+            3.12
+            3.13
+          cache: 'pip'
 
       - name: Install dependencies
-        run: |
-          python -m pip install -r requirements-ci-tests.txt
+        run: python -m pip install tox
 
-      - name: Run tests for ${{ matrix.python-version }}
+      - name: Run tox
+        run: tox
+
+      - name: Debug coverage files
+        if: failure() || always()
         run: |
-          python -m pytest -v
+          cat .coverage.json || echo "The `.coverage.json` was not found!"
+          echo "> Root dir:"
+          ls -al
+
+      # - name: Upload the JSON coverage report
+      #   if: always()
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: coverage-json
+      #     path: .coverage.json
+      #     include-hidden-files: true
+
+      # Generate the the coverage badge
+      - name: Generate coverage badge
+        uses: schneegans/dynamic-badges-action@v1.7.0
+        with:
+          coverage: .coverage.json
+          label: 'coverage'
+          style: 'flat' # You can customize this style (e.g., "flat-square", "plastic", etc.)
+          color: 'green'  # You can customize the color (e.g., 'green', 'blue', etc.)
+
+      # Optional: Upload the badge as an artifact (if you want to store it for reference)
+      - name: Upload coverage badge artifact
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: coverage-badge
+          path: coverage-badge.svg
