added coverage validation to the tests workflow

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -50,11 +50,22 @@ jobs:
       - name: Run tox
         run: tox
 
-      - name: Prepare the covbadge data
+      - name: Prepare the coverage data
         run: |
           export TOTAL_COV=$(python -c "import json; print(json.load(open('.coverage.json'))['totals']['percent_covered_display'])")
           echo total_cov=$TOTAL_COV >> $GITHUB_ENV
           echo ### Total coverage: ${TOTAL_COV}% >> $GITHUB_STEP_SUMMARY
+
+      - name: Verify the coverage data
+        env:
+          MIN_COV: 90
+        run: |
+          if (( $(echo "$TOTAL_COV < $MIN_COV" | bc -l) )); then
+            echo "ERROR: Coverage is below ${MIN_COV}% (${TOTAL_COV}%)."
+            exit 1
+          else
+            echo "Coverage is above 90% (${TOTAL_COV}%)."
+          fi
 
       - name: Generate the covbadge
         uses: schneegans/dynamic-badges-action@v1.7.0
